mybatis:
  typeAliasesPackage: com.accenture.im.repository
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/im
    username: root
    password: root
    driver-class-name: org.postgresql.Driver